string = "there is only one lord of the rings"
print(string)
print(string[2])
print(string[-1])
print(string[0:4])
print(string[2:])
print(string[2:-1])
print(string[-4:-2])
print(string[3:7:-1])
print(string[7:0:-1])
print(string[-1::-1])
print(string[::-1])
print(string[-1:-4:-1])
print(len(string))
